name: build
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
      with:
        arch: x86
    - run: luamake
    - run: ./bin/w3x2lni-lua.exe make/make.lua ci
    - uses: actions/upload-artifact@v4
      with:
        name: w3x2lni
        path: |
          bin
          data
          script
          template
          config.ini
          LICENSE.txt
          README.md
          w2l.exe
          w3x2lni.exe
    - name: Calculate the hash value  
      if: ${{ success() }}
      run: |
        Get-FileHash .\w3x2lni-win.zip | Format-List

    - name: Release
      if: ${{ success() }}
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: w3x2lni
        make_latest: ${{ inputs.make_latest }}
        prerelease: ${{ inputs.prerelease }}
        files: |
          w3x2lni-win.zip
